name: Ai pull request check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  copilot-pr-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitHub Copilot PR check
        uses: github/copilot-check@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
